# Generated by Django 4.0.5 on 2022-08-19 21:22

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miprimerapp', '0004_cafe_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='descripcion',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
